// <auto-generated />
using BolsaDeEmpleo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BolsaDeEmpleo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230622114523_migration1")]
    partial class migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BolsaDeEmpleo.Models.Applicant", b =>
                {
                    b.Property<int>("IdApplicant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdApplicant"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdApplicant");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("BolsaDeEmpleo.Models.ApplicantSkills", b =>
                {
                    b.Property<int>("IdApplicantSkills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdApplicantSkills"), 1L, 1);

                    b.Property<int>("IdApplicant")
                        .HasColumnType("int");

                    b.Property<int>("IdSkill")
                        .HasColumnType("int");

                    b.HasKey("IdApplicantSkills");

                    b.HasIndex("IdApplicant");

                    b.HasIndex("IdSkill");

                    b.ToTable("ApplicantsSkills");
                });

            modelBuilder.Entity("BolsaDeEmpleo.Models.Company", b =>
                {
                    b.Property<int>("IdCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompany"), 1L, 1);

                    b.Property<string>("NameCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCompany");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("BolsaDeEmpleo.Models.Education", b =>
                {
                    b.Property<int>("IdEducation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEducation"), 1L, 1);

                    b.Property<string>("DateCompletionStudies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdApplicant")
                        .HasColumnType("int");

                    b.Property<string>("Tittle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEducation");

                    b.HasIndex("IdApplicant");

                    b.ToTable("Education");
                });

            modelBuilder.Entity("BolsaDeEmpleo.Models.Offer", b =>
                {
                    b.Property<int>("IdOffer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOffer"), 1L, 1);

                    b.Property<int>("IdCompany")
                        .HasColumnType("int");

                    b.Property<string>("OfferDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfferTittle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOffer");

                    b.HasIndex("IdCompany");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("BolsaDeEmpleo.Models.OfferApplicants", b =>
                {
                    b.Property<int>("IdOfferApplicants")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOfferApplicants"), 1L, 1);

                    b.Property<int>("IdApplicant")
                        .HasColumnType("int");

                    b.Property<int>("IdOffer")
                        .HasColumnType("int");

                    b.HasKey("IdOfferApplicants");

                    b.HasIndex("IdApplicant");

                    b.HasIndex("IdOffer");

                    b.ToTable("OfferApplicants");
                });

            modelBuilder.Entity("BolsaDeEmpleo.Models.OfferSkills", b =>
                {
                    b.Property<int>("IdOfferSkills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOfferSkills"), 1L, 1);

                    b.Property<int>("IdOffer")
                        .HasColumnType("int");

                    b.Property<int>("IdSkill")
                        .HasColumnType("int");

                    b.HasKey("IdOfferSkills");

                    b.HasIndex("IdOffer");

                    b.HasIndex("IdSkill");

                    b.ToTable("OfferSkills");
                });

            modelBuilder.Entity("BolsaDeEmpleo.Models.Skill", b =>
                {
                    b.Property<int>("IdSkill")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSkill"), 1L, 1);

                    b.Property<string>("SkillDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSkill");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("BolsaDeEmpleo.Models.ApplicantSkills", b =>
                {
                    b.HasOne("BolsaDeEmpleo.Models.Applicant", "Applicant")
                        .WithMany("ApplicantSkillsList")
                        .HasForeignKey("IdApplicant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolsaDeEmpleo.Models.Skill", "Skill")
                        .WithMany("ApplicantSkillsList")
                        .HasForeignKey("IdSkill")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("BolsaDeEmpleo.Models.Education", b =>
                {
                    b.HasOne("BolsaDeEmpleo.Models.Applicant", "Applicant")
                        .WithMany("EducationList")
                        .HasForeignKey("IdApplicant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("BolsaDeEmpleo.Models.Offer", b =>
                {
                    b.HasOne("BolsaDeEmpleo.Models.Company", "Company")
                        .WithMany("OfferList")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("BolsaDeEmpleo.Models.OfferApplicants", b =>
                {
                    b.HasOne("BolsaDeEmpleo.Models.Applicant", "Applicant")
                        .WithMany("OfferApplicantList")
                        .HasForeignKey("IdApplicant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolsaDeEmpleo.Models.Offer", "Offer")
                        .WithMany("OfferApplicantsList")
                        .HasForeignKey("IdOffer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("BolsaDeEmpleo.Models.OfferSkills", b =>
                {
                    b.HasOne("BolsaDeEmpleo.Models.Offer", "Offer")
                        .WithMany("OfferSkillsList")
                        .HasForeignKey("IdOffer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BolsaDeEmpleo.Models.Skill", "Skill")
                        .WithMany("OfferSkillsList")
                        .HasForeignKey("IdSkill")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("BolsaDeEmpleo.Models.Applicant", b =>
                {
                    b.Navigation("ApplicantSkillsList");

                    b.Navigation("EducationList");

                    b.Navigation("OfferApplicantList");
                });

            modelBuilder.Entity("BolsaDeEmpleo.Models.Company", b =>
                {
                    b.Navigation("OfferList");
                });

            modelBuilder.Entity("BolsaDeEmpleo.Models.Offer", b =>
                {
                    b.Navigation("OfferApplicantsList");

                    b.Navigation("OfferSkillsList");
                });

            modelBuilder.Entity("BolsaDeEmpleo.Models.Skill", b =>
                {
                    b.Navigation("ApplicantSkillsList");

                    b.Navigation("OfferSkillsList");
                });
#pragma warning restore 612, 618
        }
    }
}
